---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: aurora-info-secrets
  namespace: aurora-prod
spec:
  encryptedData:
    API_KEY: AgB0jr0aKUDkfBXcmQ6D/9X8/bB6rgyHOIypiPcT8PmD3oYe89cl53APb6zAKecjQhwVZRf1JFTHOETbbwiYkNVU1zItSj3ylX5ZCg/H6ZYMp8utbd6VaicRFxoHANueLl5hEoq1c+U3ULZebGpdNVYquAlkEA5VsmgEkFZCeBlgcPCSXYdgqLdbfXVlSYtGsakfo3tF0CL2WQbr06xZQJQLTGDqykrvm9pyuzUO4i3T3RHO3bAJyZLc+Y4zqQPrQX5+4OiVNwXVABH4Z3zJCZI3jglxmtjINSgs7HLIYmxPvsqcd8U00isbOzGYMUyGJk0xhSjvqbX69UQOFISonXPiKvY81mMRAS+LhATiKE3Nu5yLR8vjtfggFRkEspwixnCrH6gEQZcfktFecK0eyp8wyL7I4WKnfiwCihyhhCsE3uDyPbIlERfJGbsRTMuTSMO/ruowIzKgQBpMNIGtfQgnY2UHWK71Y1uapUsBOAbmm9Jvc+5LIrF6XehPHyNtd24CyMOKf2mi+mZhSwxWqaLNHknJkoV2uwS/9pneVMhsT1tAWp+/XjqcaU07+zr1I5pCI9bTJAAjEZQhGDzM4G1Pf+JRcldHKoboN9flaHhWlcZUJqm0Wnyca1MzI6lsOowNXUosFA3UjqPbAcs2QYTjhf6H5GBzcJbVwsw80VGCy6C4IcfeTC7w0wI9VQ0CE/2sC9X0dnozw3XJ10bqjsy46FMhp9fXmz8WRDF155dqH4bqN/MF/amOPYMCMFk8/qUqckqbTJwrvSVdGYBBo+Zd
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: aurora-info-secrets
      namespace: aurora-prod
    type: Opaque
