apiVersion: v1
kind: Secret
metadata:
  name: aurora-info-secrets
  namespace: aurora-prod
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
type: Opaque
stringData:
  # Integration key scoped to getInfoRoomStatus, getInfoPcUsage and getSpotifyCurrentlyPlaying
  API_KEY: REPLACE_ME
