apiVersion: v1
kind: Secret
metadata:
  name: aurora-secrets
  namespace: aurora-prod
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
type: Opaque
stringData:
  COOKIE_SECRET: REPLACE_ME
  GEWIS_KEY: REPLACE_ME
  LDAP_BIND_DN_PASSWORD: REPLACE_ME
  NS_KEY: REPLACE_ME
  OIDC_CLIENT_SECRET: REPLACE_ME
  SESSION_SECRET: REPLACE_ME
  SPOTIFY_CLIENT_SECRET: REPLACE_ME
  SUDOSOS_KEY: REPLACE_ME
  TRELLO_KEY: REPLACE_ME
  TRELLO_SECRET: REPLACE_ME
  TRELLO_TOKEN: REPLACE_ME
  TYPEORM_PASSWORD: REPLACE_ME
