apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DEV_TYPE: "production"
  GIN_MODE: "release"
  RESOURCE_ENV_TYPE: "prod"
  HOST: "grooster.gewis.nl"
  BASE_PATH: "/api/v1"
  ALLOWED_ORIGINS: "https://grooster.gewis.nl"
  CLIENT_ID: "grooster-prod"
  URI_CALLBACK: "https://grooster.gewis.nl/api/v1/auth/callback"
  FRONTEND_CALLBACK: "https://grooster.gewis.nl/callback?token=%s"
  DATABASE_TYPE: "mysql"
