---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-files
  labels:
    io.kompose.service: backend-files
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  labels:
    io.kompose.service: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
