---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: oidc-secret
  namespace: room-responsible-prod
spec:
  encryptedData:
    pluginSecret: AgATgvqa7SBuv0xo2miPvBhw0fIzEdaCaItmcdfCDsESVv76vbydChw0JcUnigNPWkJTaXJ5YAjHxqikBnN6WzgkCjej9n/Nt1Z5xNb5QnCt5LNiJ+ZvgZswbbUeUELvU3ovdHFH0PUmkJZiNX0s2sqwGQ978n0Cb3UizAuv8EWxFNZjBdjciMvR8VZF7B5JIXdAubHbDJKgDBzWgyhGPTdSgGA3c4CSGHQ8XPbUUibrWvQSUn0S8GoDXB4Un3V6fr5Zc8OKad1d7WYOuT2h8xVKM2t8/glqYZPUQqv295BGEb1NG480rdazF/1G4hyosIz+7Td04iioQUZkoec8H3tq/QH+UsE64ez1HQql92taBPYl36+1/kIjttFj/snDLa9kJBRVpHNTBzp+ups5rEbSyLeXERBNsPW8yUWODpqezX0p7Ry6DRBpJKw2idkupjv4cGIN6cxSfLqvwJpNhTzljQIHfnKzvifMwgN4jQxFBRwuM5YPPPhQLNkfYKDIcemQA7bXTjZDAbhMaotPcDj9aHZKbonALE9YRJHvlQ83Ej0QIOrl0sl+qSNRBdvVj+OWYqggcaeqUZ0sJKya4M9c6nBeVrI1qFrXQBg87xbkuJCYlBHHPfu9JuauPRbGcAMhS2XRRrCxJn+gPNZcOinX7CeCFjTJ2OS1vCx2+HftZ3yleH0TNBjYKh7cO4KclEmQlMv9HBvZJim6SeXcm5I5HWzF6a/iCAKARnMNcOFB0Q==
    providerClientSecret: AgCnU/2iJsS9lCYSVTa3VX5Fa3n9HoBXfGHpnCvZpDMyKu6Qot4v2kN4PnHJvErB7HBxeBEypvP0v5aYOA8kAKOxOT1M2F0JYwd8Mi7nFKjb6oWpDCsQBiX/dexo48ms64dc/3g0i4r0zk4jHQ9+psheX8tHPSK/r7u22rghGSgkmU8WCMxyei3OjqbWdiIbcK1YbFdc9Jzcr274akfYM+nafwhk+82bGkCC0KxukkimYbIOViY4LPW8KqFFWCI2D3a0UimWtF0bvudzsLcYdI9G3yEjKYrUg0urgRrEDxLbRapsD40AD6jYWpkxrhXojz++VIDvo/8HsozPeCSt/fTZluk0uMAq17sbxIkd9LSlBFQNjVFwU4HfGJC3h12LD/ytuVExlMxR5Wz838jk6BMppsIem58QW2vA316G2isdhwy6dUI+JS8l4zBH2+11MvwrlkkPBSiwteqm/xtuJXf7ybwIR/uPIdDxLKhqGqQuBXguYNIJIRTE71Rv1rWeomBWK1aSa1NYq9Y4IJByxwicpVswhykud+UY4h5xlSN41mJ0wc9VL8db9NVYEc1BfQRBbcBTTyQUVvJzEy3n7EkOtNv9VrUKqXv4sNEEPmfdtFJ3pMWtzlYoZWAB9wNQ83xPxElubL5SpaRFKwXVPA+6GCtHj2XPMQtI0YtgwctplRrKNyj7OLQbXnyfdvjGisocRaWxHJgJ4J3x/MpbR1GyTqkL2cX/xr2/YtACyjSP8w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: oidc-secret
      namespace: room-responsible-prod
    type: Opaque
